upstream backend_servers {
    # max_fails=0 desactiva el marcado de servidores como caídos
    server worker:8000 max_fails=0 fail_timeout=5s;
    
    # OPCIONAL: Mantener conexiones abiertas para mayor velocidad
    keepalive 64;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend_servers;
        
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # Aumentar tiempos de espera para que Nginx no corte la conexión
        proxy_connect_timeout 90s;
        proxy_send_timeout 90s;
        proxy_read_timeout 90s;
    }
}
