upstream backend_servers {
    # workers
    server 127.0.0.1:8001;
    server 127.0.0.1:8002;
    # server vm_worker_ip:8000;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend_servers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}